CREATE TABLE organizations (
                               id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               name varchar(200) NOT NULL,
                               created_at timestamp with time zone NOT NULL
);

CREATE TABLE roles (
                       id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       name varchar(50) NOT NULL,
                       organization_id bigint NOT NULL,
                       created_at timestamp with time zone NOT NULL
);

CREATE TABLE users (
                       id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       email varchar(255) NOT NULL,
                       display_name varchar(150) NOT NULL,
                       password_hash varchar(255) NOT NULL,
                       organization_id bigint NOT NULL,
                       created_at timestamp with time zone NOT NULL,
                       updated_at timestamp with time zone NOT NULL
);

CREATE TABLE user_roles (
                            user_id bigint NOT NULL,
                            role_id bigint NOT NULL
);
ALTER TABLE organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE roles
    ADD CONSTRAINT uk_roles_org_name UNIQUE (organization_id, name);

ALTER TABLE user_roles
    ADD CONSTRAINT uk_user_roles_pair PRIMARY KEY (user_id, role_id);

CREATE INDEX idx_users_org_id ON users (organization_id);

ALTER TABLE roles
    ADD CONSTRAINT fk_roles_org
        FOREIGN KEY (organization_id)
            REFERENCES organizations(id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_org
        FOREIGN KEY (organization_id)
            REFERENCES organizations(id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
            REFERENCES users(id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
            REFERENCES roles(id);
